name: http_interop_shelf
description: Interop-compatible wrapper over the standard dart:io HTTP server.
version: 0.0.1
repository: https://github.com/f3ath/dart-http-interop-io

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
    http_interop: ^2.1.0
    shelf: ^1.4.2

dev_dependencies:
  lints: ^4.0.0
  cider: ^0.2.0
  test: ^1.21.1
  check_coverage: ^0.0.2

cider:
  link_template:
    tag: 'https://github.com/f3ath/dart-http-interop-io/releases/tag/%tag%'
    diff: 'https://github.com/f3ath/dart-http-interop-io/compare/%from%...%to%'
